#pragma once 

#define DEFAULT_COLOR_FORMAT VK_FORMAT_B8G8R8A8_SRGB
#define DEFAULT_DEPTH_FORMAT VK_FORMAT_D32_SFLOAT
#define DEFAULT_SHADOW_FORMAT VK_FORMAT_D32_SFLOAT
#define DEFAULT_TEXTURE_COLOR_FORMAT VK_FORMAT_R8G8B8A8_SRGB
#define MSAA_LEVEL VK_SAMPLE_COUNT_4_BIT
#define ATLAS_SIZE 16384
#define ATLAS_PADDING 0
#define SHADOW_MAP_SIZE 1024
#define MAX_VERTEX_NUMBER 1000000
#define MAX_INDEX_NUMBER 1000000
#define MAX_OBJECTS_UB 100000
#define MAX_SCENE_DATA 1
#define DEFAULT_CUSTOM_FRAG_PROPERTIES_SET_NUMBER 4