#pragma once 

#define DEFAULT_COLOR_FORMAT VK_FORMAT_B8G8R8A8_SRGB
#define DEFAULT_DEPTH_FORMAT VK_FORMAT_D32_SFLOAT
#define DEFAULT_SHADOW_FORMAT VK_FORMAT_D32_SFLOAT
#define DEFAULT_TEXTURE_COLOR_FORMAT VK_FORMAT_R8G8B8A8_SRGB
#define MSAA_LEVEL VK_SAMPLE_COUNT_1_BIT
#define ATLAS_SIZE 8096 
#define ATLAS_PADDING 4
#define SHADOW_MAP_SIZE 2048